
name: CI-CD (Build, Test, Push)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fitness-app:latest

      - name: Run container for tests
        run: |
          docker run -d -p 5000:5000 --name fitness-app ${{ secrets.DOCKER_USERNAME }}/fitness-app:latest
          sleep 5

      - name: Smoke test /health (curl 200 check)
        run: |
          chmod +x ./test.sh
          ./test.sh

      - name: Stop & remove container
        if: always()
        run: |
          docker ps -a
          docker logs fitness-app || true
          docker rm -f fitness-app || true
